imports:
  - https://github.com/aspnet/Benchmarks/blob/main/scenarios/aspnet.profiles.yml?raw=true

variables:
  serverPort: 5000
  serverScheme: http

jobs:
  benchmarks:
    source:
      repository: https://github.com/DeagleGross/aspnetcore.git
      branchOrCommit: dmkorolev/dataprotection/micro-bench
      project: src/DataProtection/DataProtection/benchmarks/Microsoft.AspNetCore.DataProtection.Benchmarks/Microsoft.AspNetCore.DataProtection.Benchmarks.csproj
    variables:
      filterArg: "*"
      jobArg: short
    arguments: --job {{jobArg}} --filter {{filterArg}} --memory
    options:
      benchmarkDotNet: true

scenarios:
  dataprotector:
    application:
      job: benchmarks

profiles:
  local:
    jobs: 
      application:
        endpoints: 
          - http://localhost:5010
