name: "Monthly Selenium Dependency Update"
description: "Automated monthly issue to update Selenium dependencies in eng/Versions.props."
title: "Monthly: Update Selenium dependencies in Versions.props"
labels:
  - dependencies
  - automation
  - selenium
assignees:
  - Copilot
body:
  - type: markdown
    attributes:
      value: |
        ## Monthly Selenium Dependency Update

        Please update the following Selenium dependencies in `eng/Versions.props` to the latest available versions:
        - `SeleniumSupportVersion`
        - `SeleniumWebDriverVersion`

        After updating, open a pull request.

        _This issue is created automatically each month and assigned to Copilot agent._
  - type: textarea
    id: update-notes
    attributes:
      label: Update Notes & Actions Taken
      description: Please describe the extra actions / info if any
      placeholder: There is a new Selenium version! https://www.selenium.dev/categories/releases/
