name: "Scheduled Issue Creation (GH CLI)"

on:
  schedule:
    - cron: '*/1 * * * *' # Every minute
  workflow_dispatch:

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Authenticate GH CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$GH_TOKEN" | gh auth login --with-token

      - name: Create Issue With Assignee
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue create \
            --repo ${{ github.repository }} \
            --assignee @copilot \
            --template "Request Browser-Testing Dependencies Update"
