name: "Scheduled Issue Creation (GH CLI)"

on:
  schedule:
    - cron: '*/1 * * * *' # Every minute
  workflow_dispatch:

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue With Assignee
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          gh issue create \
            --assignee @copilot \
            --template "Request Dep Updates"
