name: "Scheduled Issue Creation (GH CLI)"

on:
  schedule:
    # Note: The schedule below is for testing. You may want to change it.
    - cron: '0 0 * * 1' # Runs every Monday at midnight UTC
  workflow_dispatch:

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Issue From Template
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          gh issue create \
            --title "Request Browser-Testing Dependencies Update" \
            --body-file ".github/ISSUE_TEMPLATE/70_browsertesting_update_body.md"
            --assignee @copilot
