name: "Create Issue Every Minute"

on:
  schedule:
    # - cron: '0 0 1 * *' # At 00:00 UTC on the 1st of every month
    - cron: "*/1 * * * *" # Every minute
  workflow_dispatch:     # Allows manual runs for testing

jobs:
  open-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create browser-testing update issue
        uses: peter-evans/create-issue@v5
        with:
          title: "Request Browser-Testing Dependencies Update"
          labels: dependencies, automation, selenium, playwright
          assignees: Copilot
          template: 70_browsertesting_update.yml
